# Starter pipeline azure
trigger:
  - test/* # Generates an alpha codename version (because it's very imbryonic)
  - develop # Generates a beta codename (closer to release)
  - master # Official release
  - hotfix/* # Official release

variables:
  - group: release-note-auth
  - group: terraform-ci

resources:
  repositories:
    - repository: templates
      type: git
      name: azure-pipeline-templates

stages:

  - template: stages/bootstrap3.yml@templates

  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-20.04

        steps:

        - task: DownloadSecureFile@1
          name: sshKey
          displayName: 'Download SSH Key'
          inputs:
            secureFile: 'kantarware_rsa'

        - task: Bash@3
          displayName: PushToGithub
          inputs:
            targetType: inline
            workingDirectory: ./
            script: |
              export GIT_TERMINAL_PROMPT=1
              mkdir ~/.ssh && mv $(sshKey.secureFilePath) ~/.ssh/id_rsa
              chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              git remote add github git@github.com:guifabmello/terraform-azure-aks.git
              BRANCH_NAME=$(echo $(Build.SourceBranch) | cut -d/ -f3-)
              git checkout ${BRANCH_NAME} 
              git push -u github ${BRANCH_NAME}

        - task: GitHubRelease@1
          displayName: PushRelease
          inputs:
            gitHubConnection: 'guifabmello-access-token'
            repositoryName: 'guifabmello/terraform-azure-aks'
            title: $(Build.BuildNumber)
            action: 'create'
            tagSource: 'userSpecifiedTag'
            tag: $(Build.BuildNumber)
            addChangeLog: true
            assets: |
              $(Build.ArtifactStagingDirectory)/README.md
              $(Build.ArtifactStagingDirectory)/CHANGELOG.md